name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_NO_CACHE_DIR: "off"

      - name: Run Tests
        run: |
          pytest || echo "Tests failed, check the logs"

      - name: Deploy Application
        run: |
          echo "Deployment successful!"
