name: CI/CD Pipeline 279
on:
  push:
    branches:
      - main

jobs:
  build-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build-2:
    runs-on: ubuntu-latest
    needs: build-1
    steps:
      - name: Run Tests
        run: echo "Testing application"

  integration:
    runs-on: ubuntu-latest
    needs: build-2
    steps:
      - name: Integration Test
        run: echo "Integration Tests"

  deploy:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Deploy Application
        run: echo "Deploying application"
